baseURL = "/"
languageCode = "en-us"
title = ""
theme = "lit-hub"
description = "Vertcoin: The People's Coin"
Paginate = 4
[Params]
  author = "Vertcoin Documentation" 
  github = "vertcoin-project"
  twitter = "Vertcoin"


[[menu.main]]
    name = "Home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Main Site"
    weight = 200
    url = "https://vertcoin.org"
[[menu.main]]
    name = "Documentation"
    weight = 300
    url = "/docs/"
[[menu.main]]
		name = "Vertcoin Academy"
		weight = 400
		url = "/academy/"
